"""initial

Revision ID: 3f092b475bc2
Revises: 
Create Date: 2025-07-20 13:27:23.297933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f092b475bc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raiting_overall', sa.Integer(), nullable=True),
    sa.Column('points_sum', sa.Integer(), nullable=True),
    sa.Column('raiting_efficiency', sa.Integer(), nullable=True),
    sa.Column('points_efficiency', sa.Integer(), nullable=True),
    sa.Column('raiting_proactive', sa.Integer(), nullable=True),
    sa.Column('points_proactive', sa.Integer(), nullable=True),
    sa.Column('ewallet', sa.Integer(), nullable=True),
    sa.Column('lavka_exchange', sa.Integer(), nullable=True),
    sa.Column('lavka_exchange_name', sa.Integer(), nullable=True),
    sa.Column('lavka_exchange_points', sa.Integer(), nullable=True),
    sa.Column('emp_ind', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emp_ind'], ['users.emp_ind'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_emp_ind'), 'statistics', ['emp_ind'], unique=True)
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_emp_ind'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
