"""Recreate relationship table employeeinfo 2

Revision ID: 596785fd4f51
Revises: a9fcdbffa0bc
Create Date: 2025-07-22 18:56:35.858291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596785fd4f51'
down_revision: Union[str, Sequence[str], None] = 'a9fcdbffa0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_statistics_employee_id'), 'statistics', ['employee_id'], unique=True)
    op.create_foreign_key(None, 'statistics', 'employees_info', ['employee_id'], ['id'], ondelete='CASCADE')
    op.add_column('trainings', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_trainings_employee_id'), 'trainings', ['employee_id'], unique=True)
    op.create_foreign_key(None, 'trainings', 'employees_info', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_index(op.f('ix_trainings_employee_id'), table_name='trainings')
    op.drop_column('trainings', 'employee_id')
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    op.drop_index(op.f('ix_statistics_employee_id'), table_name='statistics')
    op.drop_column('statistics', 'employee_id')
    # ### end Alembic commands ###
