"""Add comments

Revision ID: a71642590a83
Revises: da0e6fc8b247
Create Date: 2025-07-23 20:33:01.246468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71642590a83'
down_revision: Union[str, Sequence[str], None] = 'da0e6fc8b247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table employees_info',
               existing_nullable=False)
    op.alter_column('employees_info', 'emp_ind',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table users',
               existing_nullable=False)
    op.alter_column('observers', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table users',
               existing_nullable=False)
    op.alter_column('statistics', 'employee_id',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table employees_info',
               existing_nullable=False)
    op.alter_column('trainings', 'employee_id',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table employees_info',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'employee_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table employees_info',
               existing_nullable=False)
    op.alter_column('statistics', 'employee_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table employees_info',
               existing_nullable=False)
    op.alter_column('observers', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table users',
               existing_nullable=False)
    op.alter_column('employees_info', 'emp_ind',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table users',
               existing_nullable=False)
    op.alter_column('admins', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table employees_info',
               existing_nullable=False)
    # ### end Alembic commands ###
