"""Recreate relationship table employeeinfo

Revision ID: a9fcdbffa0bc
Revises: e2d56c593a4c
Create Date: 2025-07-22 18:49:39.989029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fcdbffa0bc'
down_revision: Union[str, Sequence[str], None] = 'e2d56c593a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_emp_ind'), table_name='statistics')
    op.drop_constraint(op.f('statistics_emp_ind_fkey'), 'statistics', type_='foreignkey')
    op.drop_column('statistics', 'emp_ind')
    op.drop_index(op.f('ix_trainings_emp_ind'), table_name='trainings')
    op.drop_constraint(op.f('trainings_emp_ind_fkey'), 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'emp_ind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('emp_ind', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('trainings_emp_ind_fkey'), 'trainings', 'users', ['emp_ind'], ['emp_ind'], ondelete='CASCADE')
    op.create_index(op.f('ix_trainings_emp_ind'), 'trainings', ['emp_ind'], unique=True)
    op.add_column('statistics', sa.Column('emp_ind', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('statistics_emp_ind_fkey'), 'statistics', 'users', ['emp_ind'], ['emp_ind'], ondelete='CASCADE')
    op.create_index(op.f('ix_statistics_emp_ind'), 'statistics', ['emp_ind'], unique=True)
    # ### end Alembic commands ###
