"""Create table Observer

Revision ID: b8b01cd532b4
Revises: 09ca999e1fba
Create Date: 2025-07-20 14:12:42.311146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b01cd532b4'
down_revision: Union[str, Sequence[str], None] = '09ca999e1fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observers_id'), 'observers', ['id'], unique=False)
    op.create_index(op.f('ix_observers_user_id'), 'observers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observers_user_id'), table_name='observers')
    op.drop_index(op.f('ix_observers_id'), table_name='observers')
    op.drop_table('observers')
    # ### end Alembic commands ###
