"""Add comment table users

Revision ID: da0e6fc8b247
Revises: 0a3cbe393baf
Create Date: 2025-07-23 20:23:22.705709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0e6fc8b247'
down_revision: Union[str, Sequence[str], None] = '0a3cbe393baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'emp_ind',
               existing_type=sa.INTEGER(),
               comment='Foreign key for table employees_info',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'emp_ind',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key for table employees_info',
               existing_nullable=True)
    # ### end Alembic commands ###
