"""Create table Depatment

Revision ID: e2d56c593a4c
Revises: b8b01cd532b4
Create Date: 2025-07-20 14:38:17.642137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d56c593a4c'
down_revision: Union[str, Sequence[str], None] = 'b8b01cd532b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('employee_department',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees_info.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'department_id')
    )
    op.create_table('observer_department',
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['observers.id'], ),
    sa.PrimaryKeyConstraint('observer_id', 'department_id')
    )
    op.drop_column('employees_info', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_info', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('observer_department')
    op.drop_table('employee_department')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
